kv_namespaces = [
  { id = "MY_KV", binding="MY_KV" }
]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"

# Suppress esbuild side-effects warnings
[esbuild]
ignore_warnings = ["ignored-bare-import"]
